---
# The HomeKit component allows you to forward entities from Home Assistant
# to Apple HomeKit, so they can be controlled from Apple’s Home app and Siri.
#
# https://www.home-assistant.io/integrations/homekit
#
homekit:
  auto_start: false
  # Start the HomeKit Server automatically.
  # I have a Z-Wave network, but since Home Assistant restores entities,
  # we don't have to wait for it (like we did in the past).
  # The default: "Home Assistant Bridge", I like it to be just "Home Assistant"
  name: Home Assistant 🍓
  # Configuration for specific entities. Allows customization of names and types
  # These are imported from another folder, to decouple them from the packages.
  # entity_cosnfig: 
  #   !include_dir_named ../assistants/siri
  # Filters for entities to be included / excluded from HomeKit.
  filter:
    include_entities:
      - light.george
      - light.grand_lampe
      - switch.artemide_mss310_main_channel
      - switch.plant_mss310_main_channel
      - switch.prise_mss310_main_channel
      - sensor.rpi_cpu_temperature
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - camera.octoprint
      - camera.car
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - binary_sensor.main_door_open_sensor
      - binary_sensor.stair_motion_sensor
      - binary_sensor.openclose_5
      - sensor.speedtest_upload
      - sensor.speedtest_download
      - binary_sensor.car_lights
      - binary_sensor.car_running
      - sensor.car_pressure
      - sensor.car_fuel_perc
      - sensor.car_fuel
  entity_config:
    switch.prise_mss310_main_channel:
      name: Sapin de noël
    binary_sensor.car_running:
      name: Voiture allumee
      linked_battery_sensor: sensor.car_fuel_perc
      low_battery_threshold: 30
    binary_sensor.main_door_open_sensor:
      name: Capteur ouverture porte entree
      linked_battery_sensor: sensor.main_door_open_sensor_battery_level
      low_battery_threshold: 30
    binary_sensor.octoprint_printing:
      name: Impression en cours
    binary_sensor.octoprint_printing_error:
      name: Impression en erreurs
    sensor.car_battery:
      name: Voiture batterie
    sensor.speedtest_download:
      name: SpeedTest Download
    sensor.speedtest_upload:
      name: SpeedTest Upload
    sensor.octoprint_actual_bed_temp:
      name: Temperature bed
    sensor.octoprint_actual_tool0_temp:
      name: Temperature tete

